[package]
name = "swaykbdd-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
futures-lite = "2.6.0"
log = "0.4.27"
# swayipc-async = {git = "https://github.com/dydyamotya/swayipc-rs", branch="feature/async_read_write"}
swayipc-async = "2.0.4"
