name: Build and Publish Release

on:
  push:
    tags:
      - 'v*' # Run on tags starting with 'v' (e.g., v1.0.0)

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo build --profile ${{ matrix.BUILD_TARGET }}

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: swaykbdd-rs
          path: target/${{ matrix.BUILD_TARGET }}/swaykbdd-rs

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: swaykbdd-rs
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}  # Automatically use the tag that triggered the workflow
          files: |
            swaykbdd-rs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
